# Generated by Django 3.2.5 on 2021-07-22 10:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Class', models.CharField(max_length=10)),
                ('TargetExam', models.CharField(max_length=50)),
                ('Problem', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Anxiety'), (2, 'Fear of performance'), (3, 'Exam pressure'), (4, 'low self-confidence'), (5, 'stress'), (6, 'None')], max_length=11)),
                ('Query', models.CharField(max_length=500)),
                ('Mail', models.EmailField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
