# Generated by Django 3.2.5 on 2021-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='Query',
            field=models.CharField(max_length=5000),
        ),
    ]
